language: node_js
node_js:
  - "6"
before_install:
  # setting the path for phantom.js 2.0.0
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
before_script:
  - npm install -g @angular/cli
script:
  - npm run-script build:dist
  - npm run-script test:coverage