language: node_js
node_js:
  - "6"
before_install:
  # setting the path for phantom.js 2.0.0
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
before_script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages
script:
  - npm run-script build:dist
  - npm run-script test:coverage
  - ngh --repo=https://GH_TOKEN@github.com/darekplawecki/oasp4js-ng-project-seed-1.git --no-silent=true --name="GH_NAME" --email="GH_EMAIL"
after_success:
  - bash <(curl -s https://codecov.io/bash)
